#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP
function get_records(){
    if [[ -n "$2" ]]; then
        response="$(dig "$2.$1" | grep -i -A1 "answer section" | tail -n 1)"
        destination="$(echo "$response" | awk '{ print $5 }')"
        record_type="$(echo "$response" | awk '{ print $4 }')"
        echo  "The subdomain "$2" is a "$record_type" record and points to "$destination""

    else
        subdomains=(www lb-01 web-01 web-02)
        for sub_d in "${subdomains[@]}"; do
            response="$(dig "$sub_d.$1" | grep -i -A1 "answer section" | tail -n 1)"
            destination="$(echo ""$response"" | awk '{ print $5 }')"
            record_type="$(echo """$response""" | awk '{ print $4 }')"
            echo "The subdomain ""$sub_d"" is a ""$record_type"" record and points to ""$destination"""

        done
    fi

}
get_records "$1" "$2";
