#!/usr/bin/env bash
# Installs and configures nginx web server
function install_configure_nginx(){
	sudo apt-get  update
	sudo apt-get -y install nginx
	echo "Hello World" > /var/www/html/index.html
	sudo service nginx start
}
install_configure_nginx;
