#!/usr/bin/env bash
# bash script that accepts a string as argument
# Diplays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument
# passed
# pings the IP 5 times

if [ "$1" == "" ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
