#!/usr/bin/env bash
# Bash script that configures a server to kisten to port 80

rm /etc/nginx/sites-enabled/default

ln -s /etc/nginx/sites-available/defaul /etc/nginx/sites-enabled/default

service nginx restart
