#!/usr/bin/env bash
# Bash script that configures a server to listen to port 80 but shorter

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
