#!/usr/bin/env bash
# Bash script that configures a server to listen to port 80 but shorter

sed -i "s/8080/80/" /etc/nginx/sites-enabled/default

sudo service nginx restart

kill -9 "$(cat /var/run/nginx.pid)"
