#!/usr/bin/env bash
# returns numbers 1 to 100
# fizzbuzz for multiples of 3 and 5
# fizz for multiples of 3
# buzz for multiples of 5
# otherwise the number

for i in {1..100}
do
	if [ $((i % 3)) == 0 ] && [ $((i % 5)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) == 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) == 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
