#!/usr/bin/env bash
# Displays number 1-20
#displays 4 then bad luck from china
#displays 9 then badluck from japan
#dislays 17 then bad luck from italy

i=1
while [ $i -le 20 ]
do
	case $i in

	4)
		echo "$i"
		echo "bad luck from China"
		;;

	9)
		echo "$i"
		echo "bad luck from Japan"
		;;

	17)
		echo "$i"
		echo "bad luck from Italy"
		;;

	*)
		echo "$i"
		;;
	esac
	((i++))
done
